### ISSUE TITLE
AMP version not working

### ISSUE THREAD

**Issue by orballo** [frontity/saturn-theme#127] opened 2018-08-27 08:08 UTC
This failed before with https://ssr.wp-pwa.com

Link: https://amp.wp-pwa.com/?siteId=CvapQiv87z8XELLHb&type=post&id=29661&dev=true&static=https%3A%2F%2Famp.wp-pwa.com%2F&env=prod&perPage=12&device=mobile&initialUrl=https%3A%2F%2Fdominiomundial.com%2Fte-ataca-elefante%2F

**Comment by luisherranz** [comment] 2018-08-27 15:39
It works fine with the previous deployment:
https://frontity-bimmekhsaw.now.sh/?siteId=CvapQiv87z8XELLHb&type=post&id=29661&env=prod&perPage=12
but not with the current one:
https://frontity-gksfyhxurb.now.sh/?siteId=CvapQiv87z8XELLHb&type=post&id=29661&env=prod&perPage=12

I'll take a look at the changes between `saturn-app-theme-worona: v0.10.0` and `saturn-app-theme-worona: v0.9.1`

**Comment by luisherranz** [comment] 2018-08-27 15:42
Checking out these branches locally don't reproduce the problem: 
`frontity: v0.6.6`
`saturn-app-theme-worona: v0.10.0`
`wp-org-connection-app-extension-worona: v0.9.1 `

**Comment by luisherranz** [comment] 2018-08-27 15:44
Server logs are crowded with `Error retrieving options for tracking id UA-91312941-6 TypeError: Cannot read property 'UA-91312941-6' of undefined` errors so maybe we should fix that problem first.

**Comment by luisherranz** [comment] 2018-08-27 15:45
Blocked by https://github.com/frontity/frontity/issues/87

**Comment by DAreRodz** [comment] 2018-08-28 14:53
https://github.com/frontity/frontity/issues/87 fixed.

**Comment by orballo** [comment] 2018-09-06 08:45
APIs not working when calling them from Node:
https://runkit.com/luisherranz/acceso-de-las-apis-de-myr

Blocked until we get a response from the customer.

**Comment by luisherranz** [comment] 2018-09-06 13:55
I'm closing this because it should be solved when the customer solves his issue. If that's not the case, we'll reopen it again.

**Closed by luisherranz** 2018-09-06 13:55 UTC
Labels: blocked, bug, next
